### ISSUE TITLE
Request: change volume OSD background color to light in light variants

### ISSUE THREAD

**Issue by claytonwramsey** [vinceliuice/Lavanda-gtk-theme#20]
Hi! Thanks again for this great theme :).

The volume slider OSD which appears when pressing the volume keys has a dark background, even on light variants of Lavanda. It looks a little out of place:

![image](https://github.com/vinceliuice/Lavanda-gtk-theme/assets/21093136/3d602f24-3321-4b48-8012-af50cf58e9d0)

I was able to fix this by altering the definition of `$osd` in `src/sass/_colors.scss` to the following:

```scss
$osd: if($variant == "light", background(a), background(f));
```

![image](https://github.com/vinceliuice/Lavanda-gtk-theme/assets/21093136/5cb6a06c-c602-40e1-98ea-0b9d0d854273)

**Comment by claytonwramsey** [comment]
I found a better approach which doesn't also make the overview white. I made the following edits to `_osd.css`:

```scss
%osd_panel {
  // color: on($osd, secondary);
  // background-color: $osd;
  color: rgba($black, 0.6);
  background-color: $background;
  /* other properties below */
}
```
